spring.application.name=Create_Login_Account

spring.datasource.username=ENTER DB USER NAME
spring.datasource.password= ENTER DB PASSWORD HERE
spring.datasource.url=ENTER DB URL HERE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

